---
HOSTS:
  debian7:
    roles:
      - master
    platform: debian-7-amd64
    image: debian:7
    hypervisor: docker
    docker_image_commands:
      - 'apt-get install -y sudo ufw wget'
CONFIG: 
  type: foss
  log_level: info
